name: 'Helm Artifactory Publisher'
description: GitHub Action for packaging, testing helm charts and publishing to Artifactory helm repo'
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v2
    - run: ${{ github.action_path }}/main.sh
      shell: bash
